### Create user
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "username": "user",
  "password": "1234"
}

### Login user
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "user",
  "password": "1234"
}

### Login admin
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "1234"
}

### GetUserInfo
GET http://localhost:8080/user/info
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiYXV0aCI6IlJPTEVfQURNSU4iLCJleHAiOjE2NTcyNzA4MDh9.nlt4IAs0O8flCQl9vx815FuwkFCfK6ZDLV-C8sD3zC3zCMvx3xXhnsujN-HdnNJD93HYpookW7xfat-eW2CmkQ

### GetAdminInfo
GET http://localhost:8080/user/admin
Authorization: Bearer eyJhbGciOiddJIUzUxMiJ9.eyJzdWIiOiIxIasfdsdafiwiYXV0aCI6IlJPTEVfQURNSU4iLCJleHAiOjE2NTcyNzY1MjZ9.GKGJVYwz_qWryWapGcKhav8Q4KjEKlhRwhzHjEiHBetYU7WM5CcaKAKLyHSvC5EMZRljZZyC3CbdCV9-wFM1xg



### Reissue
POST http://localhost:8080/auth/reissue
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiYXV0aCI6IlJPTEVfQURNSU4iLCJleHAiOjE2NTcyNzI1OTZ9.KLSusTFBBbXlTPqoMQxbM12v_fZYT3OlZMQryWBZoNLvasA4FdbkQwcoxDd8YIQva0dlDmSDNDucUGdZV8Yq5A",
  "refreshToken": "eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE2NTcyNzA4MDZ9.kd0jcLH6uTuR4VK0d76vN1mFI9rABkvdrhVJMn_Z25uKzIyErChGpvXkTcR-J7HDKzBh9Ei6L1SYAT9ws9Sp1w"
}