### Login user
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "user",
  "password": "1234"
}

### Login admin
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "1234"
}

### GetUserInfo
GET http://localhost:8080/user/info
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY1NzQ1NjAyNH0.et1jmsodyqmY1UdhrgYVXAuCbzMovWpt13HqP57KKkw9yP1GPxC6OPfz3hBPg3gLjGmto0UTsb5ILHSxZDt72w

### GetAdminInfo
GET http://localhost:8080/user/admin
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiYXV0aCI6IlJPTEVfQURNSU4iLCJleHAiOjE2NTg3NTE4NjV9.5Iz-PNrxdAPnZwGPb_s-5g-DTjqP3PyMieZ__Ak3RzOTm17YpQ91wcTpnJaoE8K0u64HpJ4QvIPs5C3r2zol2A



### Reissue
GET http://localhost:8080/auth/reissue
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY1NzQ1NzcxMn0.mfDAHzNuUHzI1Bhx58MlwFpNmPr5oqBJnzAfIZkRdnqcGmuTE4pKMIAMgeRXSYimrog_05Ibbh52nn8vR-2ZdQ",
  "refreshToken": "eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE2NTcyNzA4MDZ9.kd0jcLH6uTuR4VK0d76vN1mFI9rABkvdrhVJMn_Z25uKzIyErChGpvXkTcR-J7HDKzBh9Ei6L1SYAT9ws9Sp1w"
}